version: '2'

networks:
  servicenet:
    driver: bridge

services:
    connote-service:
      build: ./connote-service
      ports:
        - "8081:8080"
      networks:
        - servicenet
      depends_on:
        - etcd

    customer-service:
      build: ./customer-service
      ports:
        - "8082:8080"
      networks:
        - servicenet
      depends_on:
        - etcd

    transport-service:
      build: ./transport-service
      ports:
        - "8083:8080"
      networks:
        - servicenet
      depends_on:
        - etcd

    etcd:
      image: quay.io/coreos/etcd:v2.2.5
      command: -advertise-client-urls=http://0.0.0.0:2379 -listen-client-urls=http://0.0.0.0:2379
      ports:
        - "2379:2379"
      networks:
        - servicenet
